# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3435301b-c07b-43c1-aa1b-3a53bf566fda";
    fsType = "btrfs";
    options = ["subvol=root" "compress=zstd"];
  };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/1e3e1d9f-7e0b-4ce4-91f7-ef6805a95b1e";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/3435301b-c07b-43c1-aa1b-3a53bf566fda";
    fsType = "btrfs";
    options = ["subvol=home" "compress=zstd"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/3435301b-c07b-43c1-aa1b-3a53bf566fda";
    fsType = "btrfs";
    options = ["subvol=nix" "compress=zstd" "noatime"];
  };

  fileSystems."/opt" = {
    device = "/dev/disk/by-uuid/3435301b-c07b-43c1-aa1b-3a53bf566fda";
    fsType = "btrfs";
    options = ["subvol=opt" "compress=zstd"];
  };

  fileSystems."/root" = {
    device = "/dev/disk/by-uuid/3435301b-c07b-43c1-aa1b-3a53bf566fda";
    fsType = "btrfs";
    options = ["subvol=root_user_home" "compress=zstd"];
  };

  fileSystems."/usr/local" = {
    device = "/dev/disk/by-uuid/3435301b-c07b-43c1-aa1b-3a53bf566fda";
    fsType = "btrfs";
    options = ["subvol=usr_local" "compress=zstd"];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/3435301b-c07b-43c1-aa1b-3a53bf566fda";
    fsType = "btrfs";
    options = ["subvol=var" "compress=zstd"];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/3435301b-c07b-43c1-aa1b-3a53bf566fda";
    fsType = "btrfs";
    options = ["subvol=swap" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0098-7637";
    fsType = "vfat";
  };

  swapDevices = [{device = "/swap/swapfile";}];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
